/**
 * The single source of truth for the project + scene data format.
 *
 * Everything in `shared/` is imported by BOTH the editor and the runtime
 * loader that ships inside a real game, so nothing here may depend on React
 * or on any editor UI code.
 *
 * The format is deliberately plain JSON: scene files are what the editor
 * reads, what the exporter emits, and what the game loads. There is no
 * separate "import" step that could lose data.
 */

// ---------------------------------------------------------------------------
// Assets
// ---------------------------------------------------------------------------

export type AssetKind = "image" | "spritesheet" | "tileset" | "atlas" | "audio";

export interface AssetFrame {
  name: string;
  x: number;
  y: number;
  w: number;
  h: number;
  /** Normalised 0..1 pivot. Placement and body defaults both read this. */
  pivotX: number;
  pivotY: number;
}

export interface AssetDef {
  id: string;
  /** Phaser loader key. Unique within the project. */
  key: string;
  kind: AssetKind;
  /** Virtual path inside the project, e.g. "assets/hero.png". */
  path: string;
  /** The copied bytes, as a data: URL. Assets are always copied in. */
  url: string;
  width: number;
  height: number;
  /** spritesheet + tileset */
  frameWidth?: number;
  frameHeight?: number;
  margin?: number;
  spacing?: number;
  /** atlas */
  frames?: AssetFrame[];
  /** tileset: indices flagged as colliding, authored once on the tileset. */
  tileCollides?: number[];
  /** Procedural placeholder generated by the editor rather than imported. */
  generated?: boolean;
}

// ---------------------------------------------------------------------------
// Layers — tile layers and object layers share one ordered list, because
// draw order must be one ordering and not two.
// ---------------------------------------------------------------------------

interface LayerBase {
  id: string;
  name: string;
  visible: boolean;
  locked: boolean;
}

export interface TileLayer extends LayerBase {
  kind: "tile";
  tilesetId: string;
  tileWidth: number;
  tileHeight: number;
  cols: number;
  rows: number;
  /** Row-major grid of tile indices; -1 is empty. */
  data: number[][];
}

export interface ObjectLayer extends LayerBase {
  kind: "object";
}

export type Layer = TileLayer | ObjectLayer;

// ---------------------------------------------------------------------------
// Objects
// ---------------------------------------------------------------------------

export type BodyShape = "box" | "circle";

export interface BodyDef {
  shape: BodyShape;
  width: number;
  height: number;
  radius: number;
  offsetX: number;
  offsetY: number;
  immovable: boolean;
  allowGravity: boolean;
  bounce: number;
}

export interface SceneObject {
  id: string;
  name: string;
  /** "sprite" | "container" | any key in OBJECT_DEFS. */
  type: string;
  layerId: string;
  parentId: string | null;
  x: number;
  y: number;
  /** Degrees, to keep Inspector fields human-friendly. */
  rotation: number;
  scaleX: number;
  scaleY: number;
  originX: number;
  originY: number;
  visible: boolean;
  /** Texture key + optional atlas frame. Absent for containers. */
  texture?: string;
  frame?: string;
  /** Collision group name; drives the project collision matrix. */
  group?: string;
  body?: BodyDef;
  /** Animation key played in create(). */
  playOnSpawn?: string;
  /** Set when this object is a prefab instance. */
  prefab?: string;
  /** Property path -> value, for the fields this instance overrides. */
  overrides?: Record<string, unknown>;
  /** Free-form per-instance gameplay properties. */
  data: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Prefabs
// ---------------------------------------------------------------------------

/** A prefab node is an object template: no id, no layer, no scene position. */
export type PrefabNode = Omit<
  SceneObject,
  "id" | "layerId" | "parentId" | "prefab" | "overrides"
> & { children: PrefabNode[] };

export interface PrefabDef {
  name: string;
  /** Property paths instances are allowed to override, e.g. "data.value". */
  exposed: string[];
  root: PrefabNode;
}

// ---------------------------------------------------------------------------
// Animation
// ---------------------------------------------------------------------------

export interface AnimFrameRef {
  textureKey: string;
  frame: string;
  /** ms; overrides the global fps when a pose needs to hold. */
  duration?: number;
}

export interface AnimDef {
  key: string;
  frames: AnimFrameRef[];
  fps: number;
  loop: boolean;
}

// ---------------------------------------------------------------------------
// Scenes + project
// ---------------------------------------------------------------------------

export interface SceneSettings {
  width: number;
  height: number;
  backgroundColor: string;
  gravityY: number;
  gridSize: number;
}

export interface SceneData {
  /** Stable key, also the Phaser scene key and the file name. */
  key: string;
  name: string;
  settings: SceneSettings;
  /** Index 0 renders first (bottom). Layer order === Phaser depth on export. */
  layers: Layer[];
  objects: SceneObject[];
}

/**
 * Project-wide defaults every new scene inherits, written to
 * mosaic.config.json and mirrored into the Phaser game config on export. These
 * are project config, not per-scene settings, so the tenth scene matches the
 * first.
 */
export interface ProjectConfig {
  canvas: { width: number; height: number };
  /** Drives the editor grid and the snap increment. */
  tile: number;
  scale: "FIT" | "ENVELOP" | "NONE";
  physics: "arcade" | "matter" | "none";
  /** Forces nearest-neighbour filtering and integer camera positions. */
  pixelArt: boolean;
}

export const DEFAULT_CONFIG: ProjectConfig = {
  canvas: { width: 960, height: 540 },
  tile: 32,
  scale: "FIT",
  physics: "arcade",
  pixelArt: true,
};

export type CollisionRule = "collide" | "overlap" | "ignore";

export interface ProjectData {
  name: string;
  config: ProjectConfig;
  scenes: SceneData[];
  prefabs: PrefabDef[];
  assets: AssetDef[];
  anims: AnimDef[];
  groups: string[];
  /** matrix[a][b] — symmetric; the editor keeps both halves in sync. */
  collision: Record<string, Record<string, CollisionRule>>;
}

/** One entry of the generated Phaser loader manifest. */
export interface LoaderEntry {
  key: string;
  type: "image" | "spritesheet" | "atlas" | "audio";
  url: string;
  frameConfig?: { frameWidth: number; frameHeight: number; margin: number; spacing: number };
  frames?: AssetFrame[];
}
