/**
 * The single source of truth for the project + scene data format.
 *
 * Everything in `shared/` is imported by BOTH the editor and the runtime
 * loader that ships inside a real game, so nothing here may depend on React
 * or on any editor UI code.
 *
 * The format is deliberately plain JSON: scene files are what the editor
 * reads, what the exporter emits, and what the game loads. There is no
 * separate "import" step that could lose data.
 */

// ---------------------------------------------------------------------------
// Assets
// ---------------------------------------------------------------------------

export type AssetKind = "image" | "spritesheet" | "tileset" | "atlas" | "audio";

export interface AssetFrame {
  name: string;
  x: number;
  y: number;
  w: number;
  h: number;
  /** Normalised 0..1 pivot. Placement and body defaults both read this. */
  pivotX: number;
  pivotY: number;
}

export interface AssetDef {
  id: string;
  /** Phaser loader key. Unique within the project. */
  key: string;
  kind: AssetKind;
  /** Virtual path inside the project, e.g. "assets/hero.png". */
  path: string;
  /** The copied bytes, as a data: URL. Assets are always copied in. */
  url: string;
  width: number;
  height: number;
  /** spritesheet + tileset */
  frameWidth?: number;
  frameHeight?: number;
  margin?: number;
  spacing?: number;
  /** atlas */
  frames?: AssetFrame[];
  /** tileset: indices flagged as colliding, authored once on the tileset. */
  tileCollides?: number[];
  /** Procedural placeholder generated by the editor rather than imported. */
  generated?: boolean;
}

// ---------------------------------------------------------------------------
// Layers — tile layers and object layers share one ordered list, because
// draw order must be one ordering and not two.
// ---------------------------------------------------------------------------

interface LayerBase {
  id: string;
  name: string;
  visible: boolean;
  locked: boolean;
}

export interface TileLayer extends LayerBase {
  kind: "tile";
  tilesetId: string;
  tileWidth: number;
  tileHeight: number;
  cols: number;
  rows: number;
  /** Row-major grid of tile indices; -1 is empty. */
  data: number[][];
}

export interface ObjectLayer extends LayerBase {
  kind: "object";
}

export type Layer = TileLayer | ObjectLayer;

// ---------------------------------------------------------------------------
// Objects
// ---------------------------------------------------------------------------

export type BodyShape = "box" | "circle";

export interface BodyDef {
  shape: BodyShape;
  width: number;
  height: number;
  radius: number;
  offsetX: number;
  offsetY: number;
  immovable: boolean;
  allowGravity: boolean;
  bounce: number;
}

/**
 * A script component attached to an object.
 *
 * The class lives in the project's own source tree; the scene file stores only
 * the reference and the values authored in the editor. `src` is what makes the
 * reference resolvable when two classes share a name, and it is kept even when
 * the class cannot be found, so an unresolved script is never silently dropped.
 */
export interface ScriptRef {
  /** Exported class name, e.g. "PlayerController". */
  class: string;
  /** Project-relative source path, e.g. "src/scripts/PlayerController.ts". */
  src: string;
  /** Disabled scripts are still constructed; create/update are skipped. */
  enabled: boolean;
  /** Values for the class's @property fields. Undeclared keys are stale. */
  props: Record<string, unknown>;
}

/**
 * A text object's own settings.
 *
 * Text is CONTENT — a score readout, a label, a title — so it is authored here
 * rather than built in create(). Before this existed, every visible thing in a
 * Mosaic scene could be authored except the words on it.
 */
export interface TextDef {
  content: string;
  fontFamily: string;
  /** px */
  fontSize: number;
  color: string;
  align: "left" | "center" | "right";
  /** Wrap width in px; 0 leaves it unwrapped. */
  wrapWidth: number;
  stroke?: string;
  strokeThickness?: number;
  backgroundColor?: string;
  /**
   * Pinned to the camera rather than to the world — a HUD stays put while the
   * level scrolls under it.
   */
  fixed?: boolean;
}

/**
 * Sounds an object plays for itself.
 *
 * Audio assets used to load and then never play: the loader emitted them and
 * nothing referenced them. These are the two cues that are content rather than
 * behaviour — anything conditional still belongs in a script.
 */
export interface SoundRefs {
  /** Played once, when the object is created. */
  spawn?: string;
  /**
   * Played when this object overlaps something the collision matrix pairs it
   * with. Either participant's cue fires.
   */
  overlap?: string;
}

export interface SceneObject {
  id: string;
  name: string;
  /** A rendering hint: "sprite", "text" or "container". Nothing branches on it. */
  type: string;
  layerId: string;
  parentId: string | null;
  x: number;
  y: number;
  /** Degrees, to keep Inspector fields human-friendly. */
  rotation: number;
  scaleX: number;
  scaleY: number;
  originX: number;
  originY: number;
  visible: boolean;
  /** Texture key + optional atlas frame. Absent for containers. */
  texture?: string;
  frame?: string;
  /** Collision group name; drives the project collision matrix. */
  group?: string;
  body?: BodyDef;
  /** Animation key played in create(). */
  playOnSpawn?: string;
  /** Set when this object is text rather than a sprite. */
  text?: TextDef;
  /** Audio cues the object plays for itself. */
  sounds?: SoundRefs;
  /**
   * Attached behaviour, in execution order: update() is called in list order.
   */
  scripts?: ScriptRef[];
  /** Set when this object is a prefab instance. */
  prefab?: string;
  /** Property path -> value, for the fields this instance overrides. */
  overrides?: Record<string, unknown>;
  /** Free-form per-instance gameplay properties. */
  data: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Prefabs
// ---------------------------------------------------------------------------

/**
 * A prefab node is an object template: no scene id, no layer, no scene
 * position. `prefab` and `overrides` survive, because a prefab may contain
 * another prefab's instance — which stays sealed rather than being copied in.
 */
export type PrefabNode = Omit<SceneObject, "id" | "layerId" | "parentId"> & {
  /**
   * Stable local id. Overrides, the exposure list and the propagation plan all
   * address a part by this rather than by name, so renaming a child does not
   * silently orphan what pointed at it.
   */
  lid: string;
  children: PrefabNode[];
};

/**
 * A prefab as it is STORED.
 *
 * A base prefab owns its whole tree in `root`. A variant owns nothing but a
 * `base` and a `diff`: it inherits everything and states only its differences,
 * so fixing the base fixes every variant except where one deliberately
 * disagreed. Read one through `resolvePrefab`, never straight off the field.
 */
export interface PrefabDef {
  name: string;
  /** Property paths instances are allowed to override, e.g. "data.value". */
  exposed: string[];
  /** The definition tree. Absent on a variant. */
  root?: PrefabNode;
  /** Variant: the prefab this one inherits from. */
  base?: string;
  /** Variant: property path -> value, for what this variant claims for itself. */
  diff?: Record<string, unknown>;
}

/**
 * A prefab with its inheritance applied — what an instance resolves against
 * and what the canvas draws. Never stored; always derived.
 */
export interface ResolvedPrefab {
  name: string;
  exposed: string[];
  root: PrefabNode;
  base?: string;
  /** Base first, this prefab last. A base prefab's chain is just its name. */
  chain: string[];
}

// ---------------------------------------------------------------------------
// Animation
// ---------------------------------------------------------------------------

export interface AnimFrameRef {
  textureKey: string;
  frame: string;
  /** ms; overrides the global fps when a pose needs to hold. */
  duration?: number;
}

export interface AnimDef {
  key: string;
  frames: AnimFrameRef[];
  fps: number;
  loop: boolean;
}

// ---------------------------------------------------------------------------
// Scenes + project
// ---------------------------------------------------------------------------

/**
 * The camera, as scene data.
 *
 * A level that scrolls is the normal case, and it used to be unauthorable: the
 * exporter set a background colour and world bounds and nothing else, so
 * following the player meant hand-written code in every scene.
 */
export interface CameraDef {
  /** Name of the object to follow. Empty means a fixed camera. */
  follow: string;
  /** 0..1 per axis. 1 is rigid; lower trails behind the target. */
  lerpX: number;
  lerpY: number;
  zoom: number;
  /** Clamp the camera to the scene's bounds so it never shows past the edge. */
  clampToBounds: boolean;
  /** A box in the middle the target can move inside before the camera follows. */
  deadzoneWidth: number;
  deadzoneHeight: number;
}

export const DEFAULT_CAMERA: CameraDef = {
  follow: "",
  lerpX: 1,
  lerpY: 1,
  zoom: 1,
  clampToBounds: true,
  deadzoneWidth: 0,
  deadzoneHeight: 0,
};

export interface SceneSettings {
  width: number;
  height: number;
  backgroundColor: string;
  gravityY: number;
  gridSize: number;
  /** Absent on scenes written before the camera was authorable. */
  camera?: CameraDef;
  /** Looping background music for the scene. */
  music?: { key: string; volume: number; loop: boolean };
}

export interface SceneData {
  /** Stable key, also the Phaser scene key and the file name. */
  key: string;
  name: string;
  settings: SceneSettings;
  /** Index 0 renders first (bottom). Layer order === Phaser depth on export. */
  layers: Layer[];
  objects: SceneObject[];
}

/**
 * Project-wide defaults every new scene inherits, written to
 * mosaic.config.json and mirrored into the Phaser game config on export. These
 * are project config, not per-scene settings, so the tenth scene matches the
 * first.
 */
export interface ProjectConfig {
  canvas: { width: number; height: number };
  /** Drives the editor grid and the snap increment. */
  tile: number;
  scale: "FIT" | "ENVELOP" | "NONE";
  physics: "arcade" | "matter" | "none";
  /** Forces nearest-neighbour filtering and integer camera positions. */
  pixelArt: boolean;
}

export const DEFAULT_CONFIG: ProjectConfig = {
  canvas: { width: 960, height: 540 },
  tile: 32,
  scale: "FIT",
  physics: "arcade",
  pixelArt: true,
};

export type CollisionRule = "collide" | "overlap" | "ignore";

export interface ProjectData {
  name: string;
  config: ProjectConfig;
  scenes: SceneData[];
  prefabs: PrefabDef[];
  assets: AssetDef[];
  anims: AnimDef[];
  groups: string[];
  /** matrix[a][b] — symmetric; the editor keeps both halves in sync. */
  collision: Record<string, Record<string, CollisionRule>>;
}

/** One entry of the generated Phaser loader manifest. */
export interface LoaderEntry {
  key: string;
  type: "image" | "spritesheet" | "atlas" | "audio";
  url: string;
  frameConfig?: { frameWidth: number; frameHeight: number; margin: number; spacing: number };
  frames?: AssetFrame[];
}
