import { collectLoaderManifest } from "../../shared/manifest";
import { resolveObject } from "../../shared/prefabs";
import { objectsById, worldTransform } from "../../shared/transform";
import type { ProjectData, SceneData, SceneObject, TileLayer } from "../../shared/types";

export interface GeneratedFile {
  path: string;
  contents: string;
  language: "json" | "ts";
}

export type ExportTarget = "sceneJson" | "tsSceneClass" | "both";

/**
 * The generator is pure: the same scene in produces the same bytes out, so
 * regenerating keeps diffs small enough to read in review.
 */
export function generateFiles(
  project: ProjectData,
  scene: SceneData,
  target: ExportTarget,
): GeneratedFile[] {
  const files: GeneratedFile[] = [];

  if (target === "sceneJson" || target === "both") {
    files.push({
      path: `src/scenes/${scene.key}.scene.json`,
      contents: JSON.stringify(scene, null, 2) + "\n",
      language: "json",
    });
    files.push({
      path: "phaser.editor.json",
      contents: JSON.stringify(projectManifest(project), null, 2) + "\n",
      language: "json",
    });
  }

  if (target === "tsSceneClass" || target === "both") {
    files.push({
      path: `src/scenes/${sceneClassName(scene.key)}.ts`,
      contents: generateSceneClass(project, scene),
      language: "ts",
    });
    for (const prefab of usedPrefabs(project, scene)) {
      files.push({
        path: `src/prefabs/${className(prefab)}.ts`,
        contents: generatePrefabClass(project, prefab),
        language: "ts",
      });
    }
  }

  return files;
}

/** The manifest that ships with the game: no data: URLs, just paths. */
function projectManifest(project: ProjectData) {
  return {
    name: project.name,
    scenes: project.scenes.map((s) => ({ key: s.key, name: s.name, file: `src/scenes/${s.key}.scene.json` })),
    assets: project.assets.map(({ url: _url, ...rest }) => rest),
    prefabs: project.prefabs,
    anims: project.anims,
    groups: project.groups,
    collision: project.collision,
  };
}

function usedPrefabs(project: ProjectData, scene: SceneData): string[] {
  const names = new Set<string>();
  for (const obj of scene.objects) if (obj.prefab) names.add(obj.prefab);
  return [...names].filter((n) => project.prefabs.some((p) => p.name === n)).sort();
}

/** Level_01 -> Level_01Scene */
export function sceneClassName(key: string): string {
  return `${className(key)}Scene`;
}

export function className(key: string): string {
  const cleaned = key.replace(/[^\w]+/g, "_");
  return cleaned.charAt(0).toUpperCase() + cleaned.slice(1);
}

function q(value: string): string {
  return JSON.stringify(value);
}

function varName(obj: SceneObject, used: Set<string>): string {
  let base = obj.name.replace(/[^\w]+/g, "_").replace(/^(\d)/, "_$1");
  if (!base) base = "obj";
  base = base.charAt(0).toLowerCase() + base.slice(1);
  let name = base;
  let n = 2;
  while (used.has(name)) name = `${base}${n++}`;
  used.add(name);
  return name;
}

/**
 * Emit order: preload -> create(layers bottom-up) -> colliders -> animations.
 * play-on-spawn calls are emitted with the animations, after the anims they
 * reference exist.
 */
export function generateSceneClass(project: ProjectData, scene: SceneData): string {
  const cls = sceneClassName(scene.key);
  const manifest = collectLoaderManifest(project, scene);
  const index = objectsById(scene);
  const used = new Set<string>();
  const varsById = new Map<string, string>();
  const groupVars = new Map<string, string>();
  const L: string[] = [];

  L.push(`// GENERATED by Mosaic from src/scenes/${scene.key}.scene.json`);
  L.push(`// Regenerating rewrites this file; code between the keep markers below survives.`);
  L.push(`import Phaser from "phaser";`);
  L.push(``);
  L.push(`export class ${cls} extends Phaser.Scene {`);
  L.push(`  constructor() {`);
  L.push(`    super(${q(scene.key)});`);
  L.push(`  }`);
  L.push(``);

  // ---- preload ----
  L.push(`  preload(): void {`);
  if (!manifest.length) L.push(`    // No assets referenced by this scene.`);
  for (const entry of manifest) {
    const asset = project.assets.find((a) => a.key === entry.key);
    const path = asset?.path ?? `assets/${entry.key}.png`;
    if (entry.type === "spritesheet") {
      const fc = entry.frameConfig!;
      L.push(
        `    this.load.spritesheet(${q(entry.key)}, ${q(path)}, { frameWidth: ${fc.frameWidth}, frameHeight: ${fc.frameHeight}, margin: ${fc.margin}, spacing: ${fc.spacing} });`,
      );
    } else if (entry.type === "atlas") {
      L.push(`    this.load.atlas(${q(entry.key)}, ${q(path)}, ${q(path.replace(/\.\w+$/, ".atlas.json"))});`);
    } else if (entry.type === "audio") {
      L.push(`    this.load.audio(${q(entry.key)}, ${q(path)});`);
    } else {
      const note = asset?.generated ? "  // editor placeholder — replace with real art" : "";
      L.push(`    this.load.image(${q(entry.key)}, ${q(path)});${note}`);
    }
  }
  L.push(`    // <keep id="preload">`);
  L.push(`    // </keep>`);
  L.push(`  }`);
  L.push(``);

  // ---- create ----
  L.push(`  create(): void {`);
  if (scene.settings.backgroundColor) {
    L.push(`    this.cameras.main.setBackgroundColor(${q(scene.settings.backgroundColor)});`);
  }
  L.push(
    `    this.physics.world.setBounds(0, 0, ${scene.settings.width}, ${scene.settings.height});`,
  );
  if (scene.settings.gravityY) {
    L.push(`    this.physics.world.gravity.y = ${scene.settings.gravityY};`);
  }
  L.push(``);

  scene.layers.forEach((layer, depth) => {
    if (layer.kind === "tile") {
      const tile = layer as TileLayer;
      const tileset = project.assets.find((a) => a.id === tile.tilesetId);
      if (!tileset) return;
      const v = varName({ name: tile.name } as SceneObject, used);
      L.push(`    // layer ${depth}: ${tile.name} (tiles)`);
      // Tile data stays in the .scene.json; the class reads it back so the
      // generated source does not carry thousands of literal numbers.
      L.push(
        `    const ${v}Data = (sceneData.layers[${depth}] as { data: number[][] }).data;`,
      );
      L.push(
        `    const ${v}Map = this.make.tilemap({ data: ${v}Data, tileWidth: ${tile.tileWidth}, tileHeight: ${tile.tileHeight} });`,
      );
      L.push(
        `    const ${v}Tiles = ${v}Map.addTilesetImage(${q(tileset.key)}, ${q(tileset.key)}, ${tileset.frameWidth ?? tile.tileWidth}, ${tileset.frameHeight ?? tile.tileHeight}, ${tileset.margin ?? 0}, ${tileset.spacing ?? 0})!;`,
      );
      L.push(
        `    const ${v} = ${v}Map.createLayer(0, ${v}Tiles, 0, 0, false) as Phaser.Tilemaps.TilemapLayer;`,
      );
      L.push(`    ${v}.setDepth(${depth});`);
      if (!layer.visible) L.push(`    ${v}.setVisible(false);`);
      const collides = tileset.tileCollides ?? [];
      if (collides.length) L.push(`    ${v}.setCollision([${collides.join(", ")}]);`);
      L.push(`    this.tileLayers[${q(tile.name)}] = ${v};`);
      L.push(``);
      return;
    }

    const members = scene.objects.filter((o) => o.layerId === layer.id);
    if (!members.length) return;
    L.push(`    // layer ${depth}: ${layer.name} (objects)`);
    for (const raw of members) {
      const obj = resolveObject(project, raw);
      if (obj.type === "container") continue;
      if (!obj.texture) continue;
      const world = worldTransform(raw, index);
      const v = varName(obj, used);
      varsById.set(obj.id, v);
      const factory = obj.body ? "this.physics.add.sprite" : "this.add.sprite";
      const frameArg = obj.frame ? `, ${q(obj.frame)}` : "";
      L.push(
        `    const ${v} = ${factory}(${round(world.x)}, ${round(world.y)}, ${q(obj.texture)}${frameArg});`,
      );
      L.push(`    ${v}.setName(${q(obj.name)}).setDepth(${depth});`);
      if (world.rotation) L.push(`    ${v}.setAngle(${round(world.rotation)});`);
      if (world.scaleX !== 1 || world.scaleY !== 1) {
        L.push(`    ${v}.setScale(${round(world.scaleX)}, ${round(world.scaleY)});`);
      }
      if (obj.originX !== 0.5 || obj.originY !== 0.5) {
        L.push(`    ${v}.setOrigin(${obj.originX}, ${obj.originY});`);
      }
      if (!obj.visible) L.push(`    ${v}.setVisible(false);`);
      if (obj.body) {
        const b = obj.body;
        if (b.shape === "circle") {
          L.push(`    ${v}.body.setCircle(${b.radius}, ${b.offsetX}, ${b.offsetY});`);
        } else {
          L.push(`    ${v}.body.setSize(${b.width}, ${b.height}, false);`);
          L.push(`    ${v}.body.setOffset(${b.offsetX}, ${b.offsetY});`);
        }
        if (b.immovable) L.push(`    ${v}.body.setImmovable(true);`);
        if (!b.allowGravity) L.push(`    ${v}.body.setAllowGravity(false);`);
        if (b.bounce) L.push(`    ${v}.body.setBounce(${b.bounce}, ${b.bounce});`);
      }
      for (const [k, val] of Object.entries(obj.data ?? {})) {
        L.push(`    ${v}.setData(${q(k)}, ${JSON.stringify(val)});`);
      }
      if (obj.group && obj.body) {
        let gv = groupVars.get(obj.group);
        if (!gv) {
          gv = `${obj.group.replace(/[^\w]/g, "")}Group`;
          groupVars.set(obj.group, gv);
        }
      }
      L.push(`    this.objects[${q(obj.name)}] = ${v};`);
    }
    L.push(``);
  });

  // ---- groups + colliders ----
  if (groupVars.size) {
    L.push(`    // collision groups`);
    for (const [group, gv] of groupVars) {
      const members = scene.objects
        .map((o) => resolveObject(project, o))
        .filter((o) => o.group === group && o.body && varsById.has(o.id))
        .map((o) => varsById.get(o.id)!);
      L.push(`    const ${gv} = this.physics.add.group([${members.join(", ")}]);`);
      L.push(`    this.groups[${q(group)}] = ${gv};`);
    }
    L.push(``);
    const emitted = new Set<string>();
    const pairLines: string[] = [];
    for (const [a, row] of Object.entries(project.collision ?? {})) {
      for (const [b, rule] of Object.entries(row ?? {})) {
        if (rule === "ignore") continue;
        if (!groupVars.has(a) || !groupVars.has(b)) continue;
        const key = [a, b].sort().join("|");
        if (emitted.has(key)) continue;
        emitted.add(key);
        const fn = rule === "overlap" ? "overlap" : "collider";
        const handler = rule === "overlap" ? `, this.on${className(a)}${className(b)}` : "";
        pairLines.push(
          `    this.physics.add.${fn}(${groupVars.get(a)}, ${groupVars.get(b)}${handler});`,
        );
      }
    }
    if (pairLines.length) {
      L.push(`    // collision matrix (authored once, in the project)`);
      L.push(...pairLines);
      L.push(``);
    }
    const tileLayerNames = scene.layers.filter((l) => l.kind === "tile");
    if (tileLayerNames.length) {
      for (const layer of tileLayerNames) {
        for (const gv of groupVars.values()) {
          L.push(`    this.physics.add.collider(${gv}, this.tileLayers[${q(layer.name)}]);`);
        }
      }
      L.push(``);
    }
  }

  // ---- animations ----
  const anims = usedAnims(project, scene);
  if (anims.length) {
    L.push(`    // animations`);
    for (const anim of anims) {
      L.push(`    this.anims.create({`);
      L.push(`      key: ${q(anim.key)},`);
      L.push(
        `      frames: [${anim.frames
          .map(
            (f) =>
              `{ key: ${q(f.textureKey)}, frame: ${q(f.frame)}${f.duration ? `, duration: ${f.duration}` : ""} }`,
          )
          .join(", ")}],`,
      );
      L.push(`      frameRate: ${anim.fps},`);
      L.push(`      repeat: ${anim.loop ? -1 : 0},`);
      L.push(`    });`);
    }
    for (const raw of scene.objects) {
      const obj = resolveObject(project, raw);
      const v = varsById.get(obj.id);
      if (v && obj.playOnSpawn) L.push(`    ${v}.play(${q(obj.playOnSpawn)});`);
    }
    L.push(``);
  }

  L.push(`    // <keep id="create">`);
  L.push(`    // Your own wiring goes here — it survives regeneration.`);
  L.push(`    // </keep>`);
  L.push(`  }`);
  L.push(``);
  L.push(`  update(_time: number, _delta: number): void {`);
  L.push(`    // <keep id="update">`);
  L.push(`    // </keep>`);
  L.push(`  }`);
  L.push(``);
  L.push(`  objects: Record<string, Phaser.GameObjects.Sprite> = {};`);
  L.push(`  tileLayers: Record<string, Phaser.Tilemaps.TilemapLayer> = {};`);
  L.push(`  groups: Record<string, Phaser.Physics.Arcade.Group> = {};`);
  L.push(`}`);
  L.push(``);

  const hasTiles = scene.layers.some((l) => l.kind === "tile");
  if (!hasTiles) return L.join("\n");
  const withImport = L.join("\n").replace(
    `import Phaser from "phaser";`,
    `import Phaser from "phaser";\nimport sceneData from "./${scene.key}.scene.json";`,
  );
  return withImport;
}

function usedAnims(project: ProjectData, scene: SceneData) {
  const keys = new Set<string>();
  for (const raw of scene.objects) {
    const obj = resolveObject(project, raw);
    if (obj.playOnSpawn) keys.add(obj.playOnSpawn);
  }
  return project.anims.filter((a) => keys.has(a.key));
}

export function generatePrefabClass(project: ProjectData, name: string): string {
  const prefab = project.prefabs.find((p) => p.name === name)!;
  const cls = className(name);
  const node = prefab.root;
  const L: string[] = [];
  L.push(`// GENERATED by Mosaic from prefabs/${name}.prefab.json`);
  L.push(`// The definition's properties are re-emitted on save; your methods survive.`);
  L.push(`import Phaser from "phaser";`);
  L.push(``);
  L.push(`export class ${cls} extends Phaser.Physics.Arcade.Sprite {`);
  L.push(`  constructor(scene: Phaser.Scene, x: number, y: number) {`);
  L.push(
    `    super(scene, x, y, ${q(node.texture ?? "")}${node.frame ? `, ${q(node.frame)}` : ""});`,
  );
  L.push(`    scene.add.existing(this);`);
  if (node.body) L.push(`    scene.physics.add.existing(this);`);
  if (node.originX !== 0.5 || node.originY !== 0.5) {
    L.push(`    this.setOrigin(${node.originX}, ${node.originY});`);
  }
  if (node.scaleX !== 1 || node.scaleY !== 1) {
    L.push(`    this.setScale(${node.scaleX}, ${node.scaleY});`);
  }
  if (node.body) {
    const b = node.body;
    if (b.shape === "circle") L.push(`    this.body!.setCircle(${b.radius}, ${b.offsetX}, ${b.offsetY});`);
    else {
      L.push(`    this.body!.setSize(${b.width}, ${b.height}, false);`);
      L.push(`    this.body!.setOffset(${b.offsetX}, ${b.offsetY});`);
    }
    if (b.immovable) L.push(`    this.body!.setImmovable(true);`);
    if (!b.allowGravity) L.push(`    this.body!.setAllowGravity(false);`);
  }
  for (const [k, v] of Object.entries(node.data ?? {})) {
    L.push(`    this.setData(${q(k)}, ${JSON.stringify(v)});`);
  }
  if (node.playOnSpawn) L.push(`    this.play(${q(node.playOnSpawn)});`);
  L.push(`    // <keep id="ctor">`);
  L.push(`    // </keep>`);
  L.push(`  }`);
  L.push(``);
  L.push(`  // Exposed on instances: ${prefab.exposed.join(", ") || "(nothing)"}`);
  L.push(`  // <keep id="body">`);
  L.push(`  // </keep>`);
  L.push(`}`);
  L.push(``);
  return L.join("\n");
}

function round(n: number): number {
  return Math.round(n * 100) / 100;
}
